### ISSUE TITLE
VONG-Style

### ISSUE THREAD

**Issue by dargmuesli** [greatestview/1generator#1]
Wie were es, die Website im FB [@VONG](https://www.facebook.com/VongMir/)/[DUDEN](http://www.duden.de/)/[Reclam](https://www.reclam.de/)-Style zu gestaltem? Falls michts dagegem spricht wührde ich gerne die motwemdigem Ämderumgem conmitem.

Damit meine ich eimm gelbem Himtergrumd auf dem der Name mit weiser Schrift auf eimen schcwahrzen Quadrat abgebildet is. "by greatestview.de" würde ich im die umtere limke Eke packen. Über Vorschclege bezüglich der Übersetzumgsfelder (Imput, Butdom) freue ich mich.

Vielem Dank im Vorraus :)

**Comment by greatestview** [comment]
Auch hier ferchekt das zu gelesm bigges sorry! Ich bim da vong Desigm her gamz solidarisch nit Lustige Sprüche mit Bildern umd habe derem Stil etwas zum Vorbild gemommem. Mit dem Vong-Nachmacherm kann ich michts amfamgem umd möchte die deswegem auch micht machnachem. :) Aber du kammst ja das Projekt germe forkem umd für dich selbs ampassem.

Danke dir führ deim Input auch wemm es schom über 1 Jahr her ist!

**Comment by dargmuesli** [comment]
Shon geshehem ;)
Keim Probelm!
