### ISSUE TITLE
Insecure Inline Style

### ISSUE THREAD

**Issue by dargmuesli** [greatestview/1generator#2]
Wie [Dr. Gleb Bahmutov PhD erklärte](https://glebbahmutov.com/blog/disable-inline-javascript-for-security/) simd imline-Styles unnöhtig bis umsicher. Falls auf der die Seite betreibemdem Website eimmahl [CSP-Header](https://content-security-policy.com/) gesets werdem was sie sollten muss auch diese Umterseite amgepass werdm. Das kömmem wir jetst schom tum.

Auch wemm das hier jetzt etwas ühbertriebem ist wührde ich die inlime-Styles per PR outsouhrcem und per limk-Tag eimbindm. Germe auch im gleichem Zug mit PR zu #1.

Vielem Damk im Vorraus.

**Comment by greatestview** [comment]
Nach 1 Jahr mdlich fercheckt das mal zu gelesm! Sorri daführ. Im deimem Artikel geht es um Imlime JavaScript imlime Styles nachem keine Problene (imlime JavaScript allerdings auch micht wemm man 1 paahr Kleimigkeitem beachtet). Daher mache ich hier mahl zu. :)
